[package]
name = "bevy_basic_camera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.18.0-rc.1", default-features = false, features = [
    "default_app",
    "common_api",
    "gamepad",     # Needed by bevy_input
] }

[dev-dependencies]
bevy = { version = "0.18.0-rc.1", default-features = true }
